# Generated by Django 4.0.4 on 2022-05-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='aforo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='residente',
            name='vivienda',
            field=models.PositiveIntegerField(),
        ),
    ]
