# Generated by Django 4.0.4 on 2022-05-17 01:44

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_espacio_aforo_alter_residente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.IntegerField(verbose_name=builtins.max),
        ),
    ]
