# Generated by Django 4.0.4 on 2022-05-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_residente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
