# Generated by Django 4.0.4 on 2022-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_residente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
