# Generated by Django 4.0.4 on 2022-05-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_espacio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoreserva',
            name='total',
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
                ('id_reserva', models.CharField(max_length=100, null=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residente')),
            ],
        ),
    ]
