# Generated by Django 4.0.4 on 2022-05-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pagoreserva_total_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.espacio')),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reserva')),
            ],
        ),
    ]
